import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import '@fontsource/inter/300.css'
import '@fontsource/inter/400.css'
import '@fontsource/inter/500.css'

import './globals.css'

const inter = Inter({ subsets: ['latin-ext'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={`${inter.className} min-w-fit`}>{children}</body>
    </html>
  )
}
